# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: CC0-1.0
version: 0.6.0


results_dir: 'results/'
summary_dir: 'summary/'

scenario:
  flexibility: [ 'seperate_co2_reduction' ]
  line_limits: [ 'opt' ]
  CHP_emission_accounting: [ 'dresden' ]
  co2_reduction: 0.0
  opt: ['ll']

load_year: 2020
tmin: '2020-01-01 00:00'
tmax: '2020-12-31 23:00'
freq: '8H'
frequency: 8.

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
  
enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false
  
atlite:
  nprocesses: 4
  show_progress: true
  cutouts:
   China-2020:
     module: era5
#     x: [73, 136]
#     y: [18, 54]
     dx: 0.25
     dy: 0.25
     time: ['2020', '2020']

snapshots:
  start: "2020-01-01"
  end: "2021-01-01"
  closed: 'left'

solar_thermal_angle: 45

Technique:
  solar: true
  onwind: true
  offwind: true

## add components
add_PHS: True
add_hydro: True
add_H2_storage: True
add_battery_storage: True
add_coal: True
add_nuclear: False
add_methanation: False
add_helmeth: False
add_dac: False

retrofitting: False
retrofitting-cost_factor: 1.0
retroI-fraction: 0.25
retroII-fraction: 0.55

heat_coupling: True
add_heat_pumps: True
add_boilers: True
add_chp: True
chp_parameters:
  eff_el: 0.3978
  eff_th: 0.5304
add_solar_thermal: False
solar_cf_correction: 0.788457
add_thermal_storage: True
time_dep_hp_cop: True
tes_tau: 3.

transport_coupling: False
add_v2g: False
add_bev: False
bev_availability: 0.5
transport_fuel_cell_share: 0.

renewable:
  onwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2
    potential: simple # or conservative
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  offwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    capacity_per_sqkm: 2
    correction_factor: 0.8855
    potential: simple # or conservative
    natura: true
    max_depth: 50
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  solar:
    cutout: China-2020
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2
    potential: simple # or conservative
    correction_factor: 0.85
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2

electricity:
  voltages: [220., 300., 380.]
  co2limit: 7.75e+7 # 0.05 * 3.1e9*0.5
  co2base: 1.487e+9
  agg_p_nom_limits: data/agg_p_nom_minmax.csv

  extendable_carriers:
    Generator: []
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: []

  max_hours:
    battery: 6
    H2: 168

  powerplants_filter: false # use pandas query strings here, e.g. Country not in ['Germany']
  custom_powerplants: false # use pandas query strings here, e.g. Country in ['Germany']
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_capacities_from_OPSD: [] # onwind, offwind, solar

  # estimate_renewable_capacities_from_capacity_stats:
  #   # Wind is the Fueltype in ppm.data.Capacity_stats, onwind, offwind-{ac,dc} the carrier in PyPSA-Eur
  #   Wind: [onwind, offwind-ac, offwind-dc]
  #   Solar: [solar]

hydro:
  hydro_capital_cost: False
  PHS_max_hours: 24.

costs:
  year: 2030
  discountrate: 0.07 # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  marginal_cost: # EUR/MWh
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.

plotting:
  map:
    figsize: [7, 7]
    boundaries: [60, 135., 15, 60.]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 5.e+4
      bus_size_factor_demand: 2.e+7
      bus_size_factor_heat: 5.e+4
      linewidth_factor_heat: 5.e+4

  costs_max: 10
  costs_threshold: 1

  energy_max: 24000.
  energy_min: -24000.
  energy_threshold: 50.
  loads: ['electricity', 'decentral heat', 'central heat']
  vre_techs: [ "onwind", "offwind", "solar"]
  conv_techs: [ "gas-AC", "coal", "coal-AC","solar thermal","AC-heat","AC-AC","stations-AC"]
  storage_techs: [ "hydro+PHS", "battery", "H2" ]
  load_carriers: [ "AC load" ]
  AC_carriers: [ "AC line", "AC transformer" ]
  link_carriers: [ "DC line", "Converter AC-DC" ]
  tech_colors:
    "onwind" : "#235ebc"
    "onshore wind" : "#235ebc"
    'offwind' : "#6895dd"
    'offwind-ac' : "#6895dd"
    'offshore wind' : "#6895dd"
    'offshore wind ac' : "#6895dd"
    'offwind-dc' : "#74c6f2"
    'offshore wind dc' : "#74c6f2"
    "stations-AC": "#08ad97"
    "hydro" : "#08ad97"
    "hydro+PHS" : "#08ad97"
    "PHS" : "#08ad97"
    "hydro reservoir" : "#08ad97"
    'hydroelectricity' : '#08ad97'
    "ror" : "#4adbc8"
    "run of river" : "#4adbc8"
    'solar' : "#f9d002"
    'solar PV' : "#f9d002"
    'solar thermal' : '#ffef60'
    'biomass' : '#0c6013'
    'solid biomass' : '#06540d'
    'biogas' : '#23932d'
    'waste' : '#68896b'
    'geothermal' : '#ba91b1'
    "OCGT" : "#d35050"
    "gas-AC" : "#d35050"
    "gas" : "#d35050"
    "AC-heat" : "#b20101"
    "nuclear" : "#ff9000"
    "coal" : "#707070"
    "coal-AC" : "#262626"
    "lignite" : "#9e5a01"
    "H2" : "#ea048a"
    "hydrogen storage" : "#ea048a"
    "battery" : "#b8ea04"
    "Electric load" : "#f9d002"
    "electricity" : "#f9d002"
    "central heat" : "#b8ea04"
    "decentral heat" : "#707070"
    "lines" : "#70af1d"
    "transmission lines" : "#70af1d"
    "AC-AC" : "#70af1d"
    "AC line" : "#70af1d"
    "links" : "#8a1caf"
    "HVDC links" : "#8a1caf"
    "DC-DC" : "#8a1caf"
    "DC link" : "#8a1caf"
  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind: "Offshore Wind"
    onwind: "Onshore Wind"
    solar: "Solar"
    coal: "Coal Power Plant"
    coal-AC: "Combined Heat and Power"
    gas-AC: "Open-Cycle Gas"
    PHS: "Pumped Hydro Storage"
    stations-AC: "Reservoir & Dam"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    AC-heat: "Heat Pump"
    solar thermal: "Solar Thermal"
    energy:
      coal: "Coal"
      offwind: "Offshore Wind"
      onwind: "Onshore Wind"
      solar: "Solar"
      solar thermal: "Solar Thermal"


solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    DualReductions: 0
#   solver:
#     name: cplex
#     threads: 4
#     lpmethod: 4 # barrier
#     solutiontype: 2 # non basic solution, ie no crossover
#     barrier.convergetol: 1.e-5
#     feasopt.tolerance: 1.e-6

no_lines: False
line_volume_limit_max: 5.e+15   #line_volume_limit is set = factor * max
line_cost_factor: 1