# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: CC0-1.0
version: 0.1.0

results_dir: 'results/'
summary_dir: 'summary/'

scenario:
  flexibility: [ 'seperate_co2_reduction' ]
  line_limits: [ 'opt' ]
  CHP_emission_accounting: [ 'dresden' ]
  co2_reduction: [0.0]
  opt: ['ll']


logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
  
enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false
  
atlite:
  nprocesses: 4
  show_progress: true
  cutouts:
   China-2020:
     module: era5
#     x: [73, 136]
#     y: [18, 54]
     dx: 0.25
     dy: 0.25
     time: ['2020', '2020']

snapshots:
  start: "2020-01-01"
  end: "2021-01-01"
  closed: 'left'

solar_thermal_angle: 45

Technique:
  solar: true
  onwind: true
  offwind: true

renewable:
  onwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2
    potential: simple # or conservative
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  offwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    capacity_per_sqkm: 2
    correction_factor: 0.8855
    potential: simple # or conservative
    natura: true
    max_depth: 50
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  solar:
    cutout: China-2020
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2
    potential: simple # or conservative
    correction_factor: 0.85
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2

plotting:

  costs_max: 1400
  costs_threshold: 1


  energy_max: 24000.
  energy_min: -24000.
  energy_threshold: 50.


  tech_colors:
    "coal" : "k"
    "coal power plant": "k"
    "OCGT" : "wheat"
    "onwind" : "b"
    "onshore wind" : "b"
    'offwind' : "c"
    'offshore wind' : "c"
    'solar' : "y"
    'solar PV' : "y"
    'solar thermal' : 'coral'
    "hydro" : "#3B5323"
    "inflow": "#3B5323"
    'hydroelectricity' : '#006400'
    "boiler": "orange"
    "gas boiler" : "orange"
    "gas boilers" : "orange"
    "gas boiler marginal" : "orange"
    "gas" : "brown"
    "natural gas" : "brown"
    "lines" : "green"
    "transmission lines" : "green"
    "H2" : "m"
    "hydrogen storage" : "navy"
    "hydrogen" : "navy"
    "battery" : "lawngreen"
    "storage unit": "lawngreen"
    "battery storage" : "lawngreen"
    "Nuclear" : "r"
    "Nuclear marginal" : "r"
    "Lignite" : "grey"
    "Lignite marginal" : "grey"
    "PTH" : "magenta"
    "air heat pump" : "magenta"
    "ground heat pump" : "darkmagenta"
    "resistive heater" : "pink"
    "Sabatier" : "#FF1493"
    "methanation" : "#FF1493"
    "helmeth" : "#7D0552"
    "DAC" : "#E74C3C"
    "nuclear" : "#303030"
    "water tank" : "tomato"
    "water tanks" : "tomato"
    "hot water storage" : "tomato"
    "CHP" : "r"
    "CHP heat" : "r"
    "CHP electric" : "r"
    "CHP gas": "r"
    "CHP coal": "maroon"
    "PHS" : "g"
    "Ambient" : "k"
    "Electric load" : "b"
    "Heat load" : "r"
    "Transport load" : "grey"
    "heat" : "maroon"
    "district heating" : "#CC4E5C"
    "retrofitting" : "purple"
    "building retrofitting" : "purple"
    "BEV charger" : "grey"
    "V2G" : "grey"
    "transport" : "grey"
    "electricity" : "darkseagreen"
    "central water heat" : "r"
    "central space heat": "black"
    "transport fuel cell" : "#AAAAAA"
    "decentral water heat": "pink"
    "decentral space heat": "gray"

  scenario_names:
    'seperate_co2_reduction': 'seperate-co2'
    'seperate_co2_reduction_tes': 'seperate-co2-tes'
    "el_and_heating": "El-heating"
    "elec_only" : "Electricity"
    "transport" : "Transport"
    "bev" : "DSM-50"
    "bev25" : "DSM-25"
    "bev100" : "DSM-100"
    "v2g" : "V2G-50"
    "v2g25" : "V2G-25"
    "v2g100" : "V2G-100"
    "fc25" : "FC-25"
    "fc50" : "FC-50"
    "fc100" : "FC-100"
    "base" : "Heating"
    "methanation" : "Methanation"
    "tes" : "TES"
    "central" : "Central"
    "central-tes" : "Central-TES"
    "all_flex" : "All-Flex"
    "all_flex-central" : "All-Flex-Central"

solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier.convergetol: 1.e-5
  #   feasopt.tolerance: 1.e-6

'line_volume_limit_max': 5.e+15   #line_volume_limit is set = factor * max
'line_cost_factor': 1