# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.8.0
logging_level: INFO
foresight: "myopic"

results_dir: 'results/'
summary_dir: 'summary/'

typology: "current"  # "current" or "FCG"

scenario:
  flexibility: [ 'seperate_co2_reduction' ]
  line_limits: [ 'opt' ]
  CHP_emission_accounting: [ 'dresden' ]
  co2_reduction:
    '2020': 0.0
    '2025': 0.125
    '2030': 0.25
    '2035': 0.375
    '2040': 0.5
    '2045': 0.625
    '2050': 0.75
    '2055': 0.875
    '2060': 1.0
  opts: ['ll']
  attr: 'p_nom'
  planning_horizons:
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060

tmin: '-01-01 00:00'
tmax: '-12-31 23:00'
freq: '8H'
frequency: 8.

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
  
enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false
  
atlite:
  nprocesses: 4
  show_progress: true
  cutouts:
   China-2020:
     module: era5
#     x: [73, 136]
#     y: [18, 54]
     dx: 0.25
     dy: 0.25
     time: ['2020', '2020']

solar_thermal_angle: 45

Technique:
  solar: true
  onwind: true
  offwind: true

## add components
add_PHS: True
add_hydro: True
add_H2_storage: True
add_battery_storage: True
add_coal: True
add_gas: True
add_nuclear: True
add_methanation: True
add_helmeth: True
add_dac: False

retrofitting: False
retrofitting-cost_factor: 1.0
retroI-fraction: 0.25
retroII-fraction: 0.55

heat_coupling: True
add_heat_pumps: True
add_boilers: True
add_chp: True
chp_parameters:
  eff_el: 0.3978
  eff_th: 0.5304
add_solar_thermal: False
solar_cf_correction: 0.788457
add_thermal_storage: True
time_dep_hp_cop: True
tes_tau: 3.

transport_coupling: False
add_v2g: False
add_bev: False
bev_availability: 0.5
transport_fuel_cell_share: 0.

renewable:
  onwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2
    potential: simple # or conservative
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  offwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    capacity_per_sqkm: 2
    correction_factor: 0.8855
    potential: simple # or conservative
    natura: true
    max_depth: 50
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2
  solar:
    cutout: China-2020
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2
    potential: simple # or conservative
    correction_factor: 0.85
    natura: false
    clip_p_max_pu: 1.e-2
    min_p_nom_max: 1.e-2

electricity:
  voltages: [220., 300., 380.]
  co2limit: 7.75e+7 # 0.05 * 3.1e9*0.5
  co2base: 1.487e+9
  agg_p_nom_limits: data/agg_p_nom_minmax.csv

  extendable_carriers:
    Generator: []
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: []

  max_hours:
    battery: 6
    H2: 168

  powerplants_filter: false # use pandas query strings here, e.g. Country not in ['Germany']
  custom_powerplants: false # use pandas query strings here, e.g. Country in ['Germany']
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_capacities_from_OPSD: [] # onwind, offwind, solar

  # estimate_renewable_capacities_from_capacity_stats:
  #   # Wind is the Fueltype in ppm.data.Capacity_stats, onwind, offwind-{ac,dc} the carrier in PyPSA-Eur
  #   Wind: [onwind, offwind-ac, offwind-dc]
  #   Solar: [solar]

hydro:
  hydro_capital_cost: False
  PHS_max_hours: 24.

costs:
  year: 2030
  lifetime: 25
  discountrate: 0.07 # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  marginal_cost: # EUR/MWh
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.

plotting:
  map:
    figsize: [8, 8]
    boundaries: [60, 135., 15, 60.]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 1.e+4
      cost_size_factor: 5.e+9
      bus_size_factor_demand: 2.e+7
      bus_size_factor_heat: 5.e+4
      linewidth_factor_heat: 5.e+4

  costs_max: 800
  costs_avg: 50
  costs_threshold: 1000
  costs_plots_threshold: 1

  energy_max: 18000.
  energy_min: 0.
  energy_threshold: 50.
  loads: ['electricity', 'decentral heat', 'central heat']
  vre_techs: [ "onwind", "offwind", "solar"]
  conv_techs: [ "gas", "gas-heat", "gas-AC", "AC-gas", "coal", "coal-AC","solar thermal","AC-heat","AC-AC","stations-AC","uranium", "H2-AC", "H2-gas",]
  storage_techs: [ "hydro+PHS", "battery", "AC-battery", "H2", "AC-H2" , "AC-heat"]
  load_carriers: [ "AC load" ]
  AC_carriers: [ "AC line", "AC transformer" ]
  link_carriers: [ "DC line", "Converter AC-DC" ]
  tech_colors:
    "onwind" : "#235ebc"
    "onshore wind" : "#235ebc"
    'offwind' : "#6895dd"
    'offwind-ac' : "#6895dd"
    'offshore wind' : "#6895dd"
    'offshore wind ac' : "#6895dd"
    'offwind-dc' : "#74c6f2"
    'offshore wind dc' : "#74c6f2"
    "stations-AC": "#08ad97"
    "hydro" : "#08ad97"
    "stations" : "#08ad97"
    "hydro+PHS" : "#08ad97"
    "PHS" : "#08ad97"
    "hydro reservoir" : "#08ad97"
    "hydro_inflow" : "#08ad97"
    'hydroelectricity' : '#08ad97'
    "ror" : "#4adbc8"
    "run of river" : "#4adbc8"
    'solar' : "#f9d002"
    'solar PV' : "#f9d002"
    'solar thermal' : '#ffef60'
    'biomass' : '#0c6013'
    'solid biomass' : '#06540d'
    'biogas' : '#23932d'
    'waste' : '#68896b'
    'geothermal' : '#ba91b1'
    "OCGT" : "#d35050"
    "gas-AC" : "#d35050"
    "gas" : "#d35050"
    "gas-heat": "#d35050"
    "AC-gas": "#d35050"
    "CHP": "#b20101"
    "AC-heat" : "#b20101"
    "heat pump": "#b20101"
    "nuclear" : "#ff9000"
    "uranium" : "#ff9000"
    "coal" : "#707070"
    "coal-AC" : "#262626"
    "lignite" : "#9e5a01"
    "H2" : "#ea048a"
    "AC-H2" : "#ea048a"
    "H2-AC" : "#ea048a"
    "H2-gas" : "#ea048a"
    "hydrogen storage" : "#ea048a"
    "battery" : "#b8ea04"
    "AC-battery" : "#b8ea04"
    "battery storage" : "#b8ea04"
    "Electric load" : "#f9d002"
    "electricity" : "#f9d002"
    "central heat" : "#b8ea04"
    "decentral heat" : "#707070"
    "water tanks" : "#707070"
    "lines" : "#70af1d"
    "transmission lines" : "#70af1d"
    "AC-AC" : "#70af1d"
    "AC": "#70af1d"
    "AC line" : "#70af1d"
    "links" : "#8a1caf"
    "HVDC links" : "#8a1caf"
    "DC-DC" : "#8a1caf"
    "DC link" : "#8a1caf"
  nice_names:
    CHP: "Combined Heat and Power"
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind: "Offshore Wind"
    onwind: "Onshore Wind"
    solar: "Solar"
    coal: "Coal Power Plant"
    coal-AC: "Combined Heat and Power"
    gas-AC: "Open-Cycle Gas"
    PHS: "Pumped Hydro Storage"
    stations-AC: "Reservoir & Dam"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    AC-heat: "Heat Pump"
    heat pump: "Heat Pump"
    solar thermal: "Solar Thermal"
    uranium: "Nuclear"
    energy:
      coal: "Coal"
      offwind: "Offshore Wind"
      onwind: "Onshore Wind"
      solar: "Solar"
      solar thermal: "Solar Thermal"


solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: false
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    DualReductions: 0
#   solver:
#     name: cplex
#     threads: 4
#     lpmethod: 4 # barrier
#     solutiontype: 2 # non basic solution, ie no crossover
#     barrier.convergetol: 1.e-5
#     feasopt.tolerance: 1.e-6

no_lines: False
line_volume_limit_max: 5.e+15   #line_volume_limit is set = factor * max
line_cost_factor: 1

existing_capacities:
  grouping_years: [1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060]
  threshold_capacity: 1

sector:
  district_heating:
    potential: 0.6  # maximum fraction of urban demand which can be supplied by district heating
     # increase of today's district heating demand to potential maximum district heating share
     # progress = 0 means today's district heating share, progress = 1 means maximum fraction of urban demand is supplied by district heating
    progress: 1
      # 2020: 0.0
      # 2030: 0.3
      # 2040: 0.6
      # 2050: 1.0
    district_heating_loss: 0.15
  bev_dsm_restriction_value: 0.75  #Set to 0 for no restriction on BEV DSM
  bev_dsm_restriction_time: 7  #Time at which SOC of BEV has to be dsm_restriction_value
  transport_heating_deadband_upper: 20.
  transport_heating_deadband_lower: 15.
  ICE_lower_degree_factor: 0.375  #in per cent increase in fuel consumption per degree above deadband
  ICE_upper_degree_factor: 1.6
  EV_lower_degree_factor: 0.98
  EV_upper_degree_factor: 0.63
  bev_dsm: true #turns on EV battery
  bev_availability: 0.5  #How many cars do smart charging
  bev_energy: 0.05  #average battery size in MWh
  bev_charge_efficiency: 0.9  #BEV (dis-)charging efficiency
  bev_plug_to_wheel_efficiency: 0.2 #kWh/km from EPA https://www.fueleconomy.gov/feg/ for Tesla Model S
  bev_charge_rate: 0.011 #3-phase charger with 11 kW
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  v2g: true #allows feed-in to grid from EV battery
  #what is not EV or FCEV is oil-fuelled ICE
  land_transport_fuel_cell_share: 0.15 # 1 means all FCEVs
    # 2020: 0
    # 2030: 0.05
    # 2040: 0.1
    # 2050: 0.15
  land_transport_electric_share: 0.85 # 1 means all EVs
    # 2020: 0
    # 2030: 0.25
    # 2040: 0.6
    # 2050: 0.85
  transport_fuel_cell_efficiency: 0.5
  transport_internal_combustion_efficiency: 0.3
  agriculture_machinery_electric_share: 0
  agriculture_machinery_fuel_efficiency: 0.7 # fuel oil per use
  agriculture_machinery_electric_efficiency: 0.3 # electricity per use
  shipping_average_efficiency: 0.4 #For conversion of fuel oil to propulsion in 2011
  shipping_hydrogen_liquefaction: false # whether to consider liquefaction costs for shipping H2 demands
  shipping_hydrogen_share: 1 # 1 means all hydrogen FC
    # 2020: 0
    # 2025: 0
    # 2030: 0.05
    # 2035: 0.15
    # 2040: 0.3
    # 2045: 0.6
    # 2050: 1
  time_dep_hp_cop: true #time dependent heat pump coefficient of performance
  heat_pump_sink_T: 55. # Celsius, based on DTU / large area radiators; used in build_cop_profiles.py
   # conservatively high to cover hot water and space heating in poorly-insulated buildings
  reduce_space_heat_exogenously: true  # reduces space heat demand by a given factor (applied before losses in DH)
  # this can represent e.g. building renovation, building demolition, or if
  # the factor is negative: increasing floor area, increased thermal comfort, population growth
  reduce_space_heat_exogenously_factor: 0.29 # per unit reduction in space heat demand
  # the default factors are determined by the LTS scenario from http://tool.european-calculator.eu/app/buildings/building-types-area/?levers=1ddd4444421213bdbbbddd44444ffffff11f411111221111211l212221
    # 2020: 0.10  # this results in a space heat demand reduction of 10%
    # 2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
    # 2030: 0.09
    # 2035: 0.11
    # 2040: 0.16
    # 2045: 0.21
    # 2050: 0.29
  retrofitting :  # co-optimises building renovation to reduce space heat demand
    retro_endogen: false  # co-optimise space heat savings
    cost_factor: 1.0   # weight costs for building renovation
    interest_rate: 0.04  # for investment in building components
    annualise_cost: true  # annualise the investment costs
    tax_weighting: false   # weight costs depending on taxes in countries
    construction_index: true   # weight costs depending on labour/material costs per country
  tes: true
  tes_tau: # 180 day time constant for centralised, 3 day for decentralised
    decentral: 3
    central: 180
  boilers: true
  oil_boilers: false
  chp: true
  micro_chp: false
  solar_thermal: true
  solar_cf_correction: 0.788457  # =  >>> 1/1.2683
  marginal_cost_storage: 0. #1e-4
  methanation: true
  helmeth: true
  coal_cc: false
  dac: true
  co2_vent: true
  SMR: true
  co2_sequestration_potential: 200  #MtCO2/a sequestration potential for Europe
  co2_sequestration_cost: 10   #EUR/tCO2 for sequestration of CO2
  co2_network: false
  cc_fraction: 0.9  # default fraction of CO2 captured with post-combustion capture
  hydrogen_underground_storage: true
  hydrogen_underground_storage_locations:
    # - onshore  # more than 50 km from sea
    - nearshore  # within 50 km of sea
    # - offshore
  use_fischer_tropsch_waste_heat: true
  use_fuel_cell_waste_heat: true
  electricity_distribution_grid: true
  electricity_distribution_grid_cost_factor: 1.0  #multiplies cost in data/costs.csv
  electricity_grid_connection: true  # only applies to onshore wind and utility PV
  H2_network: true
  gas_network: false
  H2_retrofit: false  # if set to True existing gas pipes can be retrofitted to H2 pipes
  # according to hydrogen backbone strategy (April, 2020) p.15
  # https://gasforclimate2050.eu/wp-content/uploads/2020/07/2020_European-Hydrogen-Backbone_Report.pdf
  # 60% of original natural gas capacity could be used in cost-optimal case as H2 capacity
  H2_retrofit_capacity_per_CH4: 0.6  # ratio for H2 capacity per original CH4 capacity of retrofitted pipelines
  gas_network_connectivity_upgrade: 1 # https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation.html#networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation
  gas_distribution_grid: true
  gas_distribution_grid_cost_factor: 1.0  #multiplies cost in data/costs.csv
  biomass_transport: false  # biomass transport between nodes
  conventional_generation: # generator : carrier
    OCGT: gas


industry:
  St_primary_fraction: 0.3 # fraction of steel produced via primary route versus secondary route (scrap+EAF); today fraction is 0.6
    # 2020: 0.6
    # 2025: 0.55
    # 2030: 0.5
    # 2035: 0.45
    # 2040: 0.4
    # 2045: 0.35
    # 2050: 0.3
  DRI_fraction: 1 # fraction of the primary route converted to DRI + EAF
    # 2020: 0
    # 2025: 0
    # 2030: 0.05
    # 2035: 0.2
    # 2040: 0.4
    # 2045: 0.7
    # 2050: 1
  H2_DRI: 1.7   #H2 consumption in Direct Reduced Iron (DRI),  MWh_H2,LHV/ton_Steel from 51kgH2/tSt in Vogl et al (2018) doi:10.1016/j.jclepro.2018.08.279
  elec_DRI: 0.322   #electricity consumption in Direct Reduced Iron (DRI) shaft, MWh/tSt HYBRIT brochure https://ssabwebsitecdn.azureedge.net/-/media/hybrit/files/hybrit_brochure.pdf
  Al_primary_fraction: 0.2 # fraction of aluminium produced via the primary route versus scrap; today fraction is 0.4
    # 2020: 0.4
    # 2025: 0.375
    # 2030: 0.35
    # 2035: 0.325
    # 2040: 0.3
    # 2045: 0.25
    # 2050: 0.2
  MWh_CH4_per_tNH3_SMR: 10.8 # 2012's demand from https://ec.europa.eu/docsroom/documents/4165/attachments/1/translations/en/renditions/pdf
  MWh_elec_per_tNH3_SMR: 0.7 # same source, assuming 94-6% split methane-elec of total energy demand 11.5 MWh/tNH3
  MWh_H2_per_tNH3_electrolysis: 6.5 # from https://doi.org/10.1016/j.joule.2018.04.017, around 0.197 tH2/tHN3 (>3/17 since some H2 lost and used for energy)
  MWh_elec_per_tNH3_electrolysis: 1.17 # from https://doi.org/10.1016/j.joule.2018.04.017 Table 13 (air separation and HB)
  NH3_process_emissions: 24.5 # in MtCO2/a from SMR for H2 production for NH3 from UNFCCC for 2015 for EU28
  petrochemical_process_emissions: 25.5 # in MtCO2/a for petrochemical and other from UNFCCC for 2015 for EU28
  HVC_primary_fraction: 1. # fraction of today's HVC produced via primary route
  HVC_mechanical_recycling_fraction: 0. # fraction of today's HVC produced via mechanical recycling
  HVC_chemical_recycling_fraction: 0. # fraction of today's HVC produced via chemical recycling
  HVC_production_today: 52. # MtHVC/a from DECHEMA (2017), Figure 16, page 107; includes ethylene, propylene and BTX
  MWh_elec_per_tHVC_mechanical_recycling: 0.547 # from SI of https://doi.org/10.1016/j.resconrec.2020.105010, Table S5, for HDPE, PP, PS, PET. LDPE would be 0.756.
  MWh_elec_per_tHVC_chemical_recycling: 6.9 # Material Economics (2019), page 125; based on pyrolysis and electric steam cracking
  chlorine_production_today: 9.58 # MtCl/a from DECHEMA (2017), Table 7, page 43
  MWh_elec_per_tCl: 3.6 # DECHEMA (2017), Table 6, page 43
  MWh_H2_per_tCl: -0.9372  # DECHEMA (2017), page 43; negative since hydrogen produced in chloralkali process
  methanol_production_today: 1.5 # MtMeOH/a from DECHEMA (2017), page 62
  MWh_elec_per_tMeOH: 0.167 # DECHEMA (2017), Table 14, page 65
  MWh_CH4_per_tMeOH: 10.25 # DECHEMA (2017), Table 14, page 65
  hotmaps_locate_missing: false
  reference_year: 2015
  # references:
  # DECHEMA (2017): https://dechema.de/dechema_media/Downloads/Positionspapiere/Technology_study_Low_carbon_energy_and_feedstock_for_the_European_chemical_industry-p-20002750.pdf
  # Material Economics (2019): https://materialeconomics.com/latest-updates/industrial-transformation-2050
